### ISSUE TITLE
MOD to MusicXML?

### ISSUE THREAD

**Issue by parkerlreed** [przem360/score2tracker#2]
Is it possible to go the other way around?

**Comment by przem360** [comment]
Not with this script.
It would be hard to impelment since MOD files do not store informations about rythmic values of notes (note durations). There are other programs that can convert MOD to MIDI and you can import MIDI to your score editor - but MIDI format also does not store informations about note duration, so the score will not be perfect.

**Comment by parkerlreed** [comment]
Ahh thanks.
